feat(--wait): don't return until DB has fully spun up

diff --git a/ephemeral-postgres b/ephemeral-postgres
--- a/ephemeral-postgres
+++ b/ephemeral-postgres
@@ -56,6 +56,7 @@ force=
 only_kill=
 list=
 shell=
+wait=
 
 if [[ -z $db_trade_name ]]; then
     echo "error: unknown DB type '$db_name'" >&2
@@ -74,13 +75,16 @@ for arg in "$@"; do
         --shell )
             shell=1
             ;;
+        --wait )
+            wait=1
+            ;;
         -k | --kill )
             only_kill=1
             ;;
         -h | --help )
             cat <<HELP
 USAGE
-    $( basename "$0" ) [-f|--force] [--shell] $( u 'IDENTIFIER' )
+    $( basename "$0" ) [-f|--force] [--shell] [--wait] $( u 'IDENTIFIER' )
     $( basename "$0" ) [-k|--kill] $( u 'IDENTIFIER' )
     $( basename "$0" ) [-h|--help]
 
@@ -95,7 +99,7 @@ HELP
             exit 0
             ;;
         -* )
-            echo "error: no such arg '$arg'" >&2
+            echo "error: invalid argument '$arg'" >&2
             exit 1
             ;;
         * )
@@ -132,11 +136,14 @@ if docker inspect "$docker_name" &> /dev/null; then
             echo "Failed to remove existing container '$docker_name'" >&2
             exit 1
         fi
-    elif [[ $shell ]]; then
+    elif [[ $shell || $wait ]]; then
+        wait_reason=shell
+        [[ $wait ]] && wait_reason=wait
+
         current_port=$( get_current_port "$docker_name" )
 
         if ! port_active "$current_port"; then
-            echo "shell: waiting for database to reach a ready state..."
+            echo "$wait_reason: waiting for database to reach a ready state..."
 
             # Wait for the server to get ready
             while ! port_active "$current_port"; do
@@ -144,8 +151,13 @@ if docker inspect "$docker_name" &> /dev/null; then
             done
         fi
 
-        echo "Connecting to '$docker_name':$current_port..."
-        "${db_name}_shell" "$identifier"
+        if [[ $shell ]]; then
+            echo "Connecting to '$docker_name':$current_port..."
+            "${db_name}_shell" "$identifier"
+        else
+            echo "wait: database ready"
+        fi
+
         exit
     else
         echo "Container '$docker_name' already exists... abort" >&2
@@ -183,15 +195,21 @@ docker run --rm -d \
     "$db_name" && {
     echo "Created new ephemeral $db_trade_name database '$docker_name':$host_port successfully"
 
-    if [[ $shell ]]; then
-        echo "shell: waiting for database to reach a ready state..."
+    if [[ $shell || $wait ]]; then
+        wait_reason=shell
+        [[ $wait ]] && wait_reason=wait
+        echo "$wait_reason: waiting for database to reach a ready state..."
 
-        # Wait for the server get ready
+        # Wait for the server to get ready
         while ! port_active "$host_port"; do
             sleep 1
         done
 
-        "${db_name}_shell" "$identifier"
+        if [[ $shell ]]; then
+            "${db_name}_shell" "$identifier"
+        else
+            echo "wait: database ready"
+        fi
     fi
 
     exit
